subroutine iniout
  
  ! initializes the netcdf output files
  
  use netcdf
  use chimere_consts
  use chimere_common
  use wholedomain_common
  implicit none
  
#define NCERR(lnum) if(ncstat/=NF90_NOERR) call nc_err(ncstat,lnum,'iniout.f90')

  !****** parameters
  !  Constant netCDF attributes
  character(len=*),parameter :: title=      'CHIMERE SUITE'
  character(len=*),parameter :: subtitle=   'Hourly output concentrations file'
  character(len=*),parameter :: generator=  'Generated by chimere'
  character(len=*),parameter :: conventions='None'
  
  !*****************************************************************************************
  ! Local variables
  ! arrays
  real(kind=8),dimension(nzonal_domain,nmerid_domain) :: buf2d
  ! strings
  character(len=1024) :: history
  character(len=15)   :: long_name
  ! scalars
  integer :: iospec
  
  integer :: ncstat
  integer :: out_time_dimid
  integer :: out_date_dimid
  integer :: out_zonal_dimid
  integer :: out_merid_dimid
  integer :: out_layers_dimid
  integer :: out_verti_dimid
  
  ! System information stuff
  character(len=32) :: systime
  character(len=64) :: hname
  character(len=32) :: usrname
  character(len=255) :: cwd
  
  
  !*****************************************************************************************
  
  ! 'get various system informations'
  call get_system(usrname,hname,systime,cwd)
  
  ! print*,'create out file'
  ncstat=nf90_create(fnout,NF90_CLOBBER,out_ncid)
  NCERR(__LINE__)
  
  ! print*,'create dimensions in out file'
  call create_dims_out
  
  ! print*,'create variables in out file'
  call create_vars_out
  
  ! print*,'write attributes to out file'
  call create_atts_out
  
  ! print*,'end define mode'
  ncstat=nf90_enddef(out_ncid)
  NCERR(__LINE__)
  
  ! print*,'record longitude and latitude'
  buf2d=xlong
  ncstat=nf90_put_var(out_ncid,out_lon_varid,buf2d)
  NCERR(__LINE__)
  buf2d=xlati
  ncstat=nf90_put_var(out_ncid,out_lat_varid,buf2d)
  NCERR(__LINE__)
  ! print*,' record vcoord coefficient'
  ncstat=nf90_put_var(out_ncid,out_avcoord_varid,avcoord)
  NCERR(__LINE__)
  ncstat=nf90_put_var(out_ncid,out_bvcoord_varid,bvcoord)
  NCERR(__LINE__)


contains
  
  !****************************************************
  subroutine create_dims_out
    implicit none
    
    ncstat=nf90_def_dim(out_ncid,'Time',        NF90_UNLIMITED,out_time_dimid)
NCERR(__LINE__)
    ncstat=nf90_def_dim(out_ncid,'DateStrLen',  dlen,          out_date_dimid)
NCERR(__LINE__)
    ncstat=nf90_def_dim(out_ncid,'west_east',   nzonal_domain,        out_zonal_dimid)
NCERR(__LINE__)
    ncstat=nf90_def_dim(out_ncid,'south_north', nmerid_domain,        out_merid_dimid)
NCERR(__LINE__)
    ncstat=nf90_def_dim(out_ncid,'bottom_top',  nivout,       out_layers_dimid)
NCERR(__LINE__)
    ncstat=nf90_def_dim(out_ncid,'vcoord_dim',  nverti,       out_verti_dimid)
NCERR(__LINE__)
  
  end subroutine create_dims_out
  
  !****************************************************
  subroutine create_atts_out
    implicit none
    
    ncstat=nf90_put_att(out_ncid,NF90_GLOBAL,'Title',title)
NCERR(__LINE__)
    ncstat=nf90_put_att(out_ncid,NF90_GLOBAL,'Sub-title',subtitle)
NCERR(__LINE__)
    ncstat=nf90_put_att(out_ncid,NF90_GLOBAL,'Chimere_type','out')
NCERR(__LINE__)
    ncstat=nf90_put_att(out_ncid,NF90_GLOBAL,'Generating_process',generator)
NCERR(__LINE__)
    ncstat=nf90_put_att(out_ncid,NF90_GLOBAL,'Conventions',conventions)
NCERR(__LINE__)
    ncstat=nf90_put_att(out_ncid,NF90_GLOBAL,'Domain',domain)
NCERR(__LINE__)
    ncstat=nf90_put_att(out_ncid,NF90_GLOBAL,'Chimere_version',version)
NCERR(__LINE__)
    
#if defined(IFORT)

    history = &
            'File '//fnout(1:len_trim(fnout))      // &
                    ' was generated on '                   // &
                    systime(1:len_trim(systime))           // &
                    ' by '                                 // &
                    usrname(1:len_trim(usrname))           // &
                    ' on '                                 // &
                    hname(1:len_trim(hname))               //'\n'C
    history = history(1:len_trim(history)-1)
    
#elif (defined(G95)+defined(PGI))

    history =                                       &
            'File '//fnout(1:len_trim(fnout))       // &
                    ' was generated on '                    // &
                    systime(1:len_trim(systime))            // &
                    ' by '                                  // &
                    usrname(1:len_trim(usrname))            // &
                    ' on '                                  // &
                    hname(1:len_trim(hname))
    history = history(1:len_trim(history)-1)
    
#else

    history='unknown'
    
#endif

    ncstat=nf90_put_att(out_ncid,NF90_GLOBAL,'history',history(1:len_trim(history)))
NCERR(__LINE__)
  
  end subroutine create_atts_out
  
  
  !****************************************************
  subroutine create_vars_out
    implicit none
    integer :: ns
    
    ! print*,' LON'
    ncstat=nf90_def_var(                                                         &
            out_ncid,                                                               &
            'lon',                                                                  &
            NF90_DOUBLE,                                                             &
            (/out_zonal_dimid,out_merid_dimid/),                                    &
            out_lon_varid                                                           &
            )
NCERR(__LINE__)
    ncstat=nf90_put_att(                                                         &
            out_ncid,                                                               &
            out_lon_varid,                                                          &
            'units',                                                                &
            'degrees_east'                                                          &
            )
NCERR(__LINE__)
    ncstat=nf90_put_att(                                                         &
            out_ncid,                                                               &
            out_lon_varid,                                                          &
            'long_name',                                                            &
            'Longitude'                                                             &
            )
NCERR(__LINE__)
    
    ! print*,' LAT'
    ncstat=nf90_def_var( &
            out_ncid, &
            'lat', &
            NF90_DOUBLE, &
            (/out_zonal_dimid,out_merid_dimid/),                                    &
            out_lat_varid                                                           &
            )
NCERR(__LINE__)
    ncstat=nf90_put_att(                                                         &
            out_ncid,                                                               &
            out_lat_varid,                                                          &
            'units',                                                                &
            'degrees_north'                                                         &
            )
NCERR(__LINE__)
    ncstat=nf90_put_att(                                                         &
            out_ncid,                                                               &
            out_lat_varid,                                                          &
            'long_name',                                                            &
            'Latitude'                                                              &
            )
NCERR(__LINE__)
    
    ! print*,' AVCOORD'
    ncstat=nf90_def_var( &
            out_ncid, &
            'a_vcoord', &
            NF90_FLOAT, &
            (/out_verti_dimid/),                                    &
            out_avcoord_varid                                                           &
            )
NCERR(__LINE__)
    ncstat=nf90_put_att(                                                         &
            out_ncid,                                                               &
            out_avcoord_varid,                                                          &
            'units',                                                                &
            'no_units'                                                         &
            )
NCERR(__LINE__)
    ncstat=nf90_put_att(                                                         &
            out_ncid,                                                               &
            out_avcoord_varid,                                                          &
            'long_name',                                                            &
            'A_sigma_coefficient'                                                              &
            )
NCERR(__LINE__)
    
    ! print*,' BVCOORD'
    ncstat=nf90_def_var( &
            out_ncid, &
            'b_vcoord', &
            NF90_FLOAT, &
            (/out_verti_dimid/),                                    &
            out_bvcoord_varid                                       &
            )
NCERR(__LINE__)
    ncstat=nf90_put_att(                                            &
            out_ncid,                                               &
            out_bvcoord_varid,                                      &
            'units',                                                &
            'no_units'                                              &
            )
NCERR(__LINE__)
    ncstat=nf90_put_att(                                            &
            out_ncid,                                               &
            out_bvcoord_varid,                                      &
            'long_name',                                            &
            'B_sigma_coefficient'                                   &
            )
NCERR(__LINE__)
    
    ! TIMES'
    ncstat=nf90_def_var(                                            &
            out_ncid,                                               &
            'Times',                                                &
            NF90_CHAR,                                              &
            (/out_date_dimid,out_time_dimid/),                      &
            out_times_varid                                         &
            )
NCERR(__LINE__)
    
    ! OUT SPECIES
    do iospec=1,noutspec
      ! set units
      ns = output_species(iospec)%iaddr
      if(species(ns)%fspec.gt.dzero) then
        output_species(iospec)%units='other' !!!!ug/m3'
      else if(species(ns)%fspec.eq.dzero) then
        output_species(iospec)%units='ppb vol dry'
      else
        output_species(iospec)%units='ppb vol wet'
      endif
      ! write values
      if (NetCDF_outtype.eq.1)then
        ncstat=nf90_def_var(                                                   &
                out_ncid,                                                      &
                output_species(iospec)%name,                                   &
                NF90_DOUBLE,                                                   &
                (/out_zonal_dimid,out_merid_dimid,out_layers_dimid,out_time_dimid/), &
                output_species(iospec)%varid                                   &
                )
      else
        ncstat=nf90_def_var(                                                   &
                out_ncid,                                                      &
                output_species(iospec)%name,                                   &
                NF90_FLOAT,                                                    &
                (/out_zonal_dimid,out_merid_dimid,out_layers_dimid,out_time_dimid/), &
                output_species(iospec)%varid                                   &
                )
      end if
      NCERR(__LINE__)
      ! write attributes
      ncstat=nf90_put_att(                                                      &
              out_ncid,                                                            &
              output_species(iospec)%varid,                                        &
              'units',                                                             &
              output_species(iospec)%units                                         &
              )
      NCERR(__LINE__)
      long_name=output_species(iospec)%name
      ncstat=nf90_put_att(                                                      &
              out_ncid,                                                            &
              output_species(iospec)%varid,                                        &
              'long_name',                                                         &
              long_name(1:len_trim(long_name))//' Concentration'                   &
              )
      NCERR(__LINE__)
    end do
    
    !    ! HLAY
    !    ncstat=nf90_def_var(out_ncid,'hlay',NF90_DOUBLE,                              &
    !         (/out_zonal_dimid,out_merid_dimid,out_layers_dimid,out_time_dimid/),    &
    !         out_hlay_varid)
    !NCERR(__LINE__)
    !    ncstat=nf90_put_att(out_ncid,out_hlay_varid,'units','meter')
    !NCERR(__LINE__)
    !    ncstat=nf90_put_att(out_ncid,out_hlay_varid,'long_name','Layer top altitude')
    !NCERR(__LINE__)
    !
    !    ! AIRM
    !    ncstat=nf90_def_var(out_ncid,'airm',NF90_DOUBLE,     &
    !         (/out_zonal_dimid,out_merid_dimid,out_layers_dimid,out_time_dimid/),    &
    !         out_airm_varid)
    !NCERR(__LINE__)
    !    ncstat=nf90_put_att(out_ncid,out_airm_varid,'units','molecule/cm**3')
    !NCERR(__LINE__)
    !    ncstat=nf90_put_att(out_ncid,out_airm_varid,'long_name','Air density')
    !NCERR(__LINE__)
    !
    !    ! RH
    !    ncstat=nf90_def_var(out_ncid,'relh',NF90_DOUBLE,     &
    !         (/out_zonal_dimid,out_merid_dimid,out_layers_dimid,out_time_dimid/),    &
    !         out_relh_varid)
    !    ncstat=nf90_put_att(out_ncid,out_relh_varid,'units','%/100')
    !    ncstat=nf90_put_att(out_ncid,out_relh_varid,'long_name','Relative Humidity')
    !NCERR(__LINE__)
    !
    !    ! TEMP
    !    ncstat=nf90_def_var(out_ncid,'temp',NF90_DOUBLE,     &
    !         (/out_zonal_dimid,out_merid_dimid,out_layers_dimid,out_time_dimid/),    &
    !         out_temp_varid)
    !NCERR(__LINE__)
    !    ncstat=nf90_put_att(out_ncid,out_temp_varid,'units','K')
    !NCERR(__LINE__)
    !    ncstat=nf90_put_att(out_ncid,out_temp_varid,'long_name','Temperature')
    !NCERR(__LINE__)
    !
  end subroutine create_vars_out

end subroutine iniout
