module message_defs

  ! This module defines some arrays used in master/worker communication
  ! For each array, it defines the address of each parameter

  ! *** int_params
  integer :: int_params_typ
  integer,dimension(:),allocatable :: int_params

  integer,parameter :: ifirst_int_params =__LINE__
  integer,parameter :: ip_nzonal      =__LINE__-ifirst_int_params
  integer,parameter :: ip_nmerid      =__LINE__-ifirst_int_params
  integer,parameter :: ip_dom_i       =__LINE__-ifirst_int_params
  integer,parameter :: ip_dom_j       =__LINE__-ifirst_int_params
  integer,parameter :: ip_wrk_comm    =__LINE__-ifirst_int_params
  integer,parameter :: ip_imstart     =__LINE__-ifirst_int_params !IP
  integer,parameter :: ip_imend	      =__LINE__-ifirst_int_params !IP
  integer,parameter :: ip_izstart     =__LINE__-ifirst_int_params !IP
  integer,parameter :: ip_izend       =__LINE__-ifirst_int_params !IP
  integer,parameter :: ip_nspec       =__LINE__-ifirst_int_params !IP
  integer,parameter :: ip_nspectot    =__LINE__-ifirst_int_params !IP
  integer,parameter :: ip_nreac    =__LINE__-ifirst_int_params !IP
  integer,parameter :: ip_nfam    =__LINE__-ifirst_int_params !IP
  integer,parameter :: ip_ndepo    =__LINE__-ifirst_int_params !IP
  integer,parameter :: ip_nreactamax =__LINE__-ifirst_int_params !IP
  integer,parameter :: ip_ntabuzen =__LINE__-ifirst_int_params !IP
  integer,parameter :: ip_nlevphot =__LINE__-ifirst_int_params !IP
  integer,parameter :: ip_nphot =__LINE__-ifirst_int_params !IP
  integer,parameter :: ip_nhourrun =__LINE__-ifirst_int_params !IP
  integer,parameter :: ip_ntemps =__LINE__-ifirst_int_params !IP
  integer,parameter :: ip_ntabmax =__LINE__-ifirst_int_params !IP
  integer,parameter :: ip_nverti =__LINE__-ifirst_int_params !IP
  integer,parameter :: ip_nphour_ref =__LINE__-ifirst_int_params !IP
  integer,parameter :: ip_ichemstep =__LINE__-ifirst_int_params !IP
  integer,parameter :: ip_usechemistry =__LINE__-ifirst_int_params !IP
  integer,parameter :: ip_usedepos =__LINE__-ifirst_int_params !IP
  integer,parameter :: ip_usewetdepos =__LINE__-ifirst_int_params !IP
  integer,parameter :: ip_useemissions =__LINE__-ifirst_int_params !IP
  integer,parameter :: ip_usetransmix =__LINE__-ifirst_int_params !IP
  integer,parameter :: ip_useabsclipconc =__LINE__-ifirst_int_params !IP
  integer,parameter :: ip_dryairout =__LINE__-ifirst_int_params !IP
  integer,parameter :: ip_nvegtype =__LINE__-ifirst_int_params !IP
  integer,parameter :: ip_nlduse =__LINE__-ifirst_int_params !IP
  integer,parameter :: ip_nsaveconcs =__LINE__-ifirst_int_params !IP
  integer,parameter :: ip_noutspec =__LINE__-ifirst_int_params !IP
  integer,parameter :: ip_nzdoms =__LINE__-ifirst_int_params !IP
  integer,parameter :: ip_nmdoms =__LINE__-ifirst_int_params !IP
  integer,parameter :: ip_nzonalmax =__LINE__-ifirst_int_params !IP
  integer,parameter :: ip_nmeridmax =__LINE__-ifirst_int_params !IP
  integer,parameter :: ip_ideepconv =__LINE__-ifirst_int_params !IP
  integer,parameter :: ip_nitgs =__LINE__-ifirst_int_params !IP
  integer,parameter :: ip_nitgssu =__LINE__-ifirst_int_params !IP
  integer,parameter :: ip_optemisb =__LINE__-ifirst_int_params !IP
  integer,parameter :: ip_nemisa =__LINE__-ifirst_int_params !IP
  integer,parameter :: ip_nemisb =__LINE__-ifirst_int_params !IP
  integer,parameter :: ip_ndep =__LINE__-ifirst_int_params !IP
  integer,parameter :: ip_nlevemis =__LINE__-ifirst_int_params !IP
  integer,parameter :: ip_ihoursu =__LINE__-ifirst_int_params !IP
  integer,parameter :: ip_fwd =__LINE__-ifirst_int_params !IP
  integer,parameter :: ip_tl =__LINE__-ifirst_int_params !IP
  integer,parameter :: ip_ad =__LINE__-ifirst_int_params !IP
  integer,parameter :: ip_hpulse =__LINE__-ifirst_int_params !IP
  integer,parameter :: nb_int_params  =__LINE__-ifirst_int_params-1


  ! *** dbl_params
  integer :: dbl_params_typ
  real(kind=8),dimension(:),allocatable :: dbl_params
  
  integer,parameter :: ifirst_dbl_params =__LINE__
  integer,parameter :: ip_soltim      =__LINE__-ifirst_dbl_params
  integer,parameter :: ip_djul        =__LINE__-ifirst_dbl_params
  integer,parameter :: ip_clipconc    =__LINE__-ifirst_dbl_params
  integer,parameter :: ip_psurf       =__LINE__-ifirst_dbl_params
  integer,parameter :: nb_dbl_params  =__LINE__-ifirst_dbl_params-1

  ! *** Here we define the addresses used by MPI to send/receive messages
  ! These adresses are arbitrary but must be unique


integer,parameter :: ias_int_params              =__LINE__
integer,parameter :: ias_hourly_int_params       =__LINE__
integer,parameter :: ias_dbl_params              =__LINE__
integer,parameter :: ias_frac_hourly_dbl_params  =__LINE__
integer,parameter :: ias_idaero                  =__LINE__
integer,parameter :: ias_nsecti                  =__LINE__
integer,parameter :: ias_inemisa                 =__LINE__
integer,parameter :: ias_inemisb                 =__LINE__
integer,parameter :: ias_ncompo                  =__LINE__
integer,parameter :: ias_inaq                    =__LINE__
integer,parameter :: ias_inh2so4                 =__LINE__
integer,parameter :: ias_ntypesp1                =__LINE__
integer,parameter :: ias_iprofemipb              =__LINE__
integer,parameter :: ias_kreacl                  =__LINE__
integer,parameter :: ias_kreacp                  =__LINE__
integer,parameter :: ias_nreactants              =__LINE__
integer,parameter :: ias_inwetd                  =__LINE__
integer,parameter :: ias_ityperate               =__LINE__
integer,parameter :: ias_iphoto                  =__LINE__
integer,parameter :: ias_indepo                  =__LINE__
integer,parameter :: ias_numi                    =__LINE__
integer,parameter :: ias_numesoc                 =__LINE__
integer,parameter :: ias_nsaq                    =__LINE__
integer,parameter :: ias_imine                   =__LINE__
integer,parameter :: ias_inemipa                 =__LINE__
integer,parameter :: ias_inemipb                 =__LINE__
integer,parameter :: ias_ntypesp                 =__LINE__
integer,parameter :: ias_imonth                  =__LINE__
integer,parameter :: ias_ihour                   =__LINE__
integer,parameter :: ias_idtyp                   =__LINE__
integer,parameter :: ias_nwetd                   =__LINE__
integer,parameter :: ias_ispecemip               =__LINE__
integer,parameter :: ias_incloud                 =__LINE__
integer,parameter :: ias_insu                    =__LINE__
integer,parameter :: ias_innh                    =__LINE__
integer,parameter :: ias_inni                    =__LINE__
integer,parameter :: ias_inexcha                 =__LINE__
integer,parameter :: ias_iexcha                  =__LINE__
integer,parameter :: ias_insvol                  =__LINE__
integer,parameter :: ias_indic_aeroorg           =__LINE__
integer,parameter :: ias_iposorg                 =__LINE__
integer,parameter :: ias_tabaeroorg              =__LINE__
integer,parameter :: ias_vectorg                 =__LINE__
integer,parameter :: ias_conc_tl                 =__LINE__
integer,parameter :: ias_conc                    =__LINE__
integer,parameter :: ias_aconc                   =__LINE__
integer,parameter :: ias_excha                   =__LINE__
integer,parameter :: ias_conc_halo               =__LINE__
integer,parameter :: ias_aconc_halo              =__LINE__
integer,parameter :: ias_conc_bounds_tl          =__LINE__
integer,parameter :: ias_conc_bounds             =__LINE__
integer,parameter :: ias_aconc_bounds            =__LINE__
integer,parameter :: iar_aconc_bounds            =__LINE__
integer,parameter :: ias_conc_top_tl             =__LINE__
integer,parameter :: ias_conc_top                =__LINE__
integer,parameter :: ias_aconc_top               =__LINE__
integer,parameter :: iar_aconc_top               =__LINE__
integer,parameter :: ias_conco_tl                =__LINE__
integer,parameter :: ias_conco                   =__LINE__
integer,parameter :: ias_aconco                  =__LINE__
integer,parameter :: ias_exchao                  =__LINE__
integer,parameter :: ias_winzloc                 =__LINE__
integer,parameter :: ias_winmloc                 =__LINE__
integer,parameter :: ias_thlayloc                =__LINE__
integer,parameter :: ias_airmloc                 =__LINE__
integer,parameter :: ias_zunit                   =__LINE__
integer,parameter :: ias_evaprof                 =__LINE__
integer,parameter :: ias_ireacl                  =__LINE__
integer,parameter :: ias_ireacp                  =__LINE__
integer,parameter :: ias_irctt                   =__LINE__
integer,parameter :: ias_stoi                    =__LINE__
integer,parameter :: ias_coefac                  =__LINE__
integer,parameter :: ias_xsize                   =__LINE__
integer,parameter :: ias_ysize                   =__LINE__
integer,parameter :: ias_emipaloc                =__LINE__
integer,parameter :: ias_emisbloc                =__LINE__
integer,parameter :: ias_emipbloc                =__LINE__
integer,parameter :: ias_emisaloc_tl             =__LINE__
integer,parameter :: ias_emisaloc                =__LINE__
integer,parameter :: ias_hlayloc                 =__LINE__
integer,parameter :: ias_zeniloc                 =__LINE__
integer,parameter :: ias_emisb_tl                =__LINE__
integer,parameter :: ias_emisb                   =__LINE__
integer,parameter :: ias_winz                    =__LINE__
integer,parameter :: ias_winm                    =__LINE__
integer,parameter :: ias_temp                    =__LINE__
integer,parameter :: ias_sphu                    =__LINE__
integer,parameter :: ias_airm                    =__LINE__
integer,parameter :: ias_hlay                    =__LINE__
integer,parameter :: ias_kzzz                    =__LINE__
integer,parameter :: ias_clwc                    =__LINE__
! lmbb deep convection
integer,parameter :: ias_ideep                   =__LINE__
integer,parameter :: ias_dpeu                    =__LINE__
integer,parameter :: ias_dped                    =__LINE__
integer,parameter :: ias_dpdu                    =__LINE__
integer,parameter :: ias_dpdd                    =__LINE__
! lmbb deep convection
integer,parameter :: ias_hght                    =__LINE__
integer,parameter :: ias_atte                    =__LINE__
integer,parameter :: ias_tem2                    =__LINE__
integer,parameter :: ias_usta                    =__LINE__
integer,parameter :: ias_aerr                    =__LINE__
integer,parameter :: ias_obuk                    =__LINE__
integer,parameter :: ias_wsta                    =__LINE__
integer,parameter :: ias_topc                    =__LINE__
integer,parameter :: ias_sreh                    =__LINE__
integer,parameter :: ias_boundtop                =__LINE__
integer,parameter :: ias_xbasx                   =__LINE__
integer,parameter :: ias_xbasy                   =__LINE__
integer,parameter :: ias_ybasx                   =__LINE__
integer,parameter :: ias_ybasy                   =__LINE__
integer,parameter :: ias_psurf                   =__LINE__
integer,parameter :: ias_slati                   =__LINE__
integer,parameter :: ias_clati                   =__LINE__
integer,parameter :: ias_xlong                   =__LINE__
integer,parameter :: ias_xlati                   =__LINE__
integer,parameter :: ias_deptmin                 =__LINE__
integer,parameter :: ias_deptopt                 =__LINE__
integer,parameter :: ias_depvpd1                 =__LINE__
integer,parameter :: ias_depvpd2                 =__LINE__
integer,parameter :: ias_depsgs                  =__LINE__
integer,parameter :: ias_depegs                  =__LINE__
integer,parameter :: ias_depsgl                  =__LINE__
integer,parameter :: ias_deplai1                 =__LINE__
integer,parameter :: ias_deplai2                 =__LINE__
integer,parameter :: ias_depegl                  =__LINE__
integer,parameter :: ias_depphe1                 =__LINE__
integer,parameter :: ias_depphe0                 =__LINE__
integer,parameter :: ias_depphe2                 =__LINE__
integer,parameter :: ias_depalph                 =__LINE__
integer,parameter :: ias_gmax                    =__LINE__
integer,parameter :: ias_fmin                    =__LINE__
integer,parameter :: ias_zcanopy                 =__LINE__
integer,parameter :: ias_rgso3                   =__LINE__
integer,parameter :: ias_so2rh                   =__LINE__
integer,parameter :: ias_rgsso2                  =__LINE__
integer,parameter :: ias_factrb                  =__LINE__
integer,parameter :: ias_factd                   =__LINE__
integer,parameter :: ias_rm                      =__LINE__
integer,parameter :: ias_dhx                     =__LINE__
integer,parameter :: ias_df0                     =__LINE__
integer,parameter :: ias_zunitu                  =__LINE__
integer,parameter :: ias_fveg                    =__LINE__
integer,parameter :: ias_dland                   =__LINE__
integer,parameter :: ias_zetaref                 =__LINE__
integer,parameter :: ias_altiphot                =__LINE__
integer,parameter :: ias_photoj                  =__LINE__
integer,parameter :: ias_tabrate                 =__LINE__
integer,parameter :: ias_tabtemp                 =__LINE__
integer,parameter :: ias_zsu                     =__LINE__
integer,parameter :: ias_znh                     =__LINE__
integer,parameter :: ias_zni                     =__LINE__
integer,parameter :: ias_rhi                     =__LINE__
integer,parameter :: ias_tempi                   =__LINE__
integer,parameter :: ias_zf                      =__LINE__
integer,parameter :: ias_ds                      =__LINE__
integer,parameter :: ias_vs                      =__LINE__
integer,parameter :: ias_species_varid           =__LINE__
integer,parameter :: ias_species_transp          =__LINE__
integer,parameter :: ias_species_transpv         =__LINE__
integer,parameter :: ias_species_bounddry         =__LINE__
integer,parameter :: ias_species_name            =__LINE__
integer,parameter :: ias_emiprof                 =__LINE__
integer,parameter :: ias_kparloc                 =__LINE__
integer,parameter :: ias_t0L                     =__LINE__
integer,parameter :: ias_p0L                     =__LINE__
integer,parameter :: ias_a0L                     =__LINE__
integer,parameter :: ias_dKoa0                   =__LINE__
integer,parameter :: ias_dAoa                    =__LINE__
integer,parameter :: ias_dToa                    =__LINE__
integer,parameter :: ias_dKh0                    =__LINE__
integer,parameter :: ias_dAh                     =__LINE__
integer,parameter :: ias_dTh                     =__LINE__
integer,parameter :: ias_koc                     =__LINE__
integer,parameter :: ias_kdoc                    =__LINE__
integer,parameter :: ias_diffair                 =__LINE__
integer,parameter :: ias_diffwat                 =__LINE__
integer,parameter :: ias_ksea                    =__LINE__
integer,parameter :: ias_ksoil                   =__LINE__

!lm add time-steps
integer,parameter :: ias_nphour              =__LINE__
integer,parameter :: ias_dtr                 =__LINE__
integer,parameter :: ias_dtr2                =__LINE__
! jlm
integer,parameter :: ias_os_fscpe                =__LINE__
integer,parameter :: ias_os_varid                =__LINE__
integer,parameter :: ias_os_iaddr                =__LINE__
integer,parameter :: ias_os_name                 =__LINE__
integer,parameter :: ias_os_units                =__LINE__
integer,parameter :: ias_ns                      =__LINE__
integer,parameter :: ias_nelem                   =__LINE__
integer,parameter :: ias_ifam                    =__LINE__

integer,parameter :: iar_conc                    =__LINE__
integer,parameter :: iar_conc_tl                 =__LINE__
integer,parameter :: iar_aconc                   =__LINE__
integer,parameter :: iar_excha                   =__LINE__
integer,parameter :: iar_conc_halo               =__LINE__
integer,parameter :: iar_aconc_halo              =__LINE__
integer,parameter :: iar_conc_halo_h             =__LINE__
integer,parameter :: iar_aconc_halo_h            =__LINE__
integer,parameter :: iar_conco                   =__LINE__
integer,parameter :: iar_conco_tl                =__LINE__
integer,parameter :: iar_aconco                  =__LINE__
integer,parameter :: iar_exchao                  =__LINE__
integer,parameter :: iar_drydep                  =__LINE__
integer,parameter :: iar_drydep_tl               =__LINE__
integer,parameter :: iar_wetdep                  =__LINE__
integer,parameter :: iar_wetdep_tl               =__LINE__
integer,parameter :: iar_airmloc                 =__LINE__
integer,parameter :: iar_winzloc                 =__LINE__
integer,parameter :: iar_winmloc                 =__LINE__
integer,parameter :: iar_winvloc                 =__LINE__
integer,parameter :: iar_sphuloc                 =__LINE__
integer,parameter :: iar_temploc                 =__LINE__
integer,parameter :: iar_winxloc                 =__LINE__
integer,parameter :: iar_hlayloc                 =__LINE__
integer,parameter :: iar_thlayloc                =__LINE__
integer,parameter :: iar_clwcloc                 =__LINE__
integer,parameter :: iar_presloc                 =__LINE__
integer,parameter :: iar_depoloc                 =__LINE__
integer,parameter :: iar_hghtloc                 =__LINE__
integer,parameter :: iar_atteloc                 =__LINE__
integer,parameter :: iar_zeniloc                 =__LINE__
integer,parameter :: iar_tem2loc                 =__LINE__
integer,parameter :: iar_ustaloc                 =__LINE__
integer,parameter :: iar_aerrloc                 =__LINE__
integer,parameter :: iar_obukloc                 =__LINE__
integer,parameter :: iar_wstaloc                 =__LINE__
integer,parameter :: iar_topcloc                 =__LINE__
integer,parameter :: iar_kzzzloc                 =__LINE__
integer,parameter :: iar_toprint                 =__LINE__
integer,parameter :: iar_aemisb                  =__LINE__
integer,parameter :: iar_aemisaloc               =__LINE__
integer,parameter :: ias_aemisb                  =__LINE__
integer,parameter :: ias_aemisaloc               =__LINE__
! IP pour obs
integer,parameter :: ias_nobs                    =__LINE__
integer,parameter :: ias_tabobs                  =__LINE__
integer,parameter :: iar_tabobs                  =__LINE__
! IP
integer,parameter :: ias_chckexch                =__LINE__



end module message_defs
